### ISSUE TITLE
Error when sending email with attachment 

### ISSUE THREAD

**Issue by stephenlacy** [kalys/bamboo_ses#45]
When an email contains an attachment that does not include a `content_id` elixir raises a `** (KeyError) key :content_id not found in: %{data: "<binary>"}` 

https://github.com/kalys/bamboo_ses/blob/38217296ac5286f5a6b59fa679d6fb09e63188f8/lib/bamboo/adapters/ses_adapter.ex#L75 should check if the key exists rather than check if it has a value.
```elixir
Map.has_key?(attachment, :content_id)
```

**Comment by kalys** [comment]
Hey @stevelacy .

I'll fix this bug within 2 days.

BTW could you provide bamboo & bamboo_ses version?

**Comment by stevelacy** [comment]
Sounds good!

```elixir
      {:bamboo, "~> 2.2.0"},
      {:bamboo_ses, "~> 0.2.0"},

```

**Comment by kalys** [comment]
I cannot reproduce this bug.

The problem is you have only `data` field in attachment struct and bamboo_ses requires also `content_id` and `filename`. Which means when your problem with `content_id` will be solved there will be a problem with `filename`.

According to the source code here (https://github.com/thoughtbot/bamboo/blob/main/lib/bamboo/attachment.ex) there should be all fields.

Could you share how you construct an attachment struct?
And share library versions from mix.lock.

**Comment by stevelacy** [comment]
```elixir
params = %{
  to: email,
  attachments: [
    %{
      filename: "file.png",
      data: file,
      type: "image/png",
      content_id: nil
    }
  ]
}

```
The `path` is not required, odd that content_id would be.
